Dev/wucke13 refactor runtime runner
DLR-FT/wasm-interpreter pull request #56
Opened 2024-07-26 23:02 UTC by wucke13

### Pull Request Overview

Moves the interpreter loop to its own, dedicated file and ensures that the `RuntimeInstance::run` function only yields `RuntimeError`s.

### Testing Strategy

Tested by `cargo test`

### TODO or Help Wanted

This pull request still needs approval, I clearly think it is a good idea to have this one gigantous function in its own, dedicated file, but maybe there is objection. Also, maybe `instructions.rs` is not the best name, possibly we could name it differently, like `interpreter_loop`? In the end, its not so important, because it wont be visible in the non-public documentation, and when browsing the code it should be clear that the biggest source code file named `instructions.rs` is where actually all instructions are implemented.

### Formatting

- [x] Ran `cargo fmt`
- [x] Ran `cargo check`
- [x] Ran `cargo build`
- [x] Ran `cargo doc`
- [x] Ran `nix fmt`
- [ ] Ran `treefmt`

2024-07-29 08:03 UTC, nerodesu017 approved these changes

2024-07-30 07:25 UTC, florianhartung requested changes

2024-07-30 08:35 UTC, wucke13 commented on src/execution/instructions.rs
> +    pub(super) fn function(&mut self, idx: FuncIdx, stack: &mut Stack) -> Result<(), RuntimeError> {
Good catch, thank you! Now resolved.

2024-07-30 09:07 UTC, florianhartung approved these changes

2024-07-31 08:24 UTC, nerodesu017 approved these changes

2024-07-31 08:26 UTC, merged