feat: f64 operations
DLR-FT/wasm-interpreter pull request #65
Opened 2024-08-06 14:03 UTC by nerodesu017

### Pull Request Overview

This pull request adds f64-related op codes.

### Testing Strategy

This pull request was tested locally.

### TODO or Help Wanted

N/A

### Formatting

- [x] Ran `cargo fmt`
- [x] Ran `cargo check`
- [x] Ran `cargo build`
- [x] Ran `cargo doc`
- [ ] Ran `nix fmt`
- [ ] Ran `treefmt`

### Github Issue

This pull request implements issue #2

2024-08-06 14:07 UTC, valexandru commented on src/execution/mod.rs
> +// pub mod ;
```suggestion
```

2024-08-06 14:09 UTC, florianhartung requested changes

2024-08-06 14:09 UTC, florianhartung commented on src/core/reader/types/values.rs
> +
Would this be possible here instead?

```suggestion
        let bytes = self.strip_bytes::<8>().map_err(|_| Error::Eof)?;
        let word = u64::from_le_bytes(bytes);
```

2024-08-06 14:42 UTC, florianhartung commented on src/core/reader/types/values.rs
> +
This should also be possible:
```rs
let bytes = self.strip_bytes::<{ std::mem::size_of::<u64>() }>().map_err(|_| Error::Eof)?;
```

2024-08-06 15:39 UTC, nerodesu017 commented on src/core/reader/types/values.rs
> +
Used first suggestion

2024-08-06 16:00 UTC, florianhartung approved these changes

2024-08-20 08:59 UTC, george-cosma approved these changes

2024-08-20 09:20 UTC, valexandru approved these changes

2024-08-20 09:20 UTC, merged