feat: conversion op codes
DLR-FT/wasm-interpreter pull request #79
Opened 2024-08-28 14:11 UTC by nerodesu017

### Pull Request Overview

This pull request adds conversion op codes.

### Testing Strategy

This pull request was tested using (almost) all related tests from the [Wasm TestSuite](https://github.com/WebAssembly/testsuite)

### TODO or Help Wanted

N/A

### Formatting

- [X] Ran `cargo fmt`
- [X] Ran `cargo check`
- [X] Ran `cargo build`
- [X] Ran `cargo doc`
- [ ] Ran `nix fmt`

### Github Issue

This pull request partially implements #2

2024-08-28 14:44 UTC, wucke13 commented on tests/conversions.rs
> +use core::{f32, f64};
Please add attribution to the original source of this

2024-09-03 11:09 UTC, florianhartung requested changes

2024-09-03 11:09 UTC, florianhartung commented on src/execution/value.rs
> +
Please remove this if it's not needed anymore

2024-09-09 12:23 UTC, florianhartung submitted a review, later dismissed

2024-09-10 09:52 UTC, florianhartung approved these changes

2024-09-10 10:12 UTC, george-cosma approved these changes

2024-09-10 10:13 UTC, merged